# This is first github workflow
name: App Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    # fetch code from repo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.7"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-projects: true

      - name: Load cached venv
        uses: actions/cache@v4
        id: cached-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependency using poetry
        if: steps.cached-dependencies.outputs.cache-hit != 'true'
        run: poetry run make install
